//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3tr0viCh.Database.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P3tr0viCh.Database.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER={0};PORT={1};DATABASE={2};USER={3};PASSWORD={4};.
        /// </summary>
        internal static string ConnectionFireBird {
            get {
                return ResourceManager.GetString("ConnectionFireBird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER={0};PORT={1};DATABASE={2};USER={3};PASSWORD={4};SSL MODE={5};.
        /// </summary>
        internal static string ConnectionStringMySql {
            get {
                return ResourceManager.GetString("ConnectionStringMySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NONE.
        /// </summary>
        internal static string ConnectionStringMySqlSslNone {
            get {
                return ResourceManager.GetString("ConnectionStringMySqlSslNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREFERRED.
        /// </summary>
        internal static string ConnectionStringMySqlSslPreferred {
            get {
                return ResourceManager.GetString("ConnectionStringMySqlSslPreferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA SOURCE={0};VERSION=3;FOREIGN KEYS=TRUE;.
        /// </summary>
        internal static string ConnectionStringSQLite {
            get {
                return ResourceManager.GetString("ConnectionStringSQLite", resourceCulture);
            }
        }
    }
}
